version: "3"
services:
    wordpress:
        image: wordpress:latest
        container_name: "wordpress"
        ports:
        #localhost:8080でwordpressにアクセスできる
        - "8080:80"
        volumes:
            # テーマをマウント
            - "./themes:/var/www/html/wp-content/themes"
            - "$PWD/.docker/backup:/tmp/backup"
            - "$PWD/.docker/log:/tmp/log"
            # プラグインをマウントしたい場合
            - "./plugins:/var/www/html/wp-content/plugins"
            # アップロード画像をマウントしたい場合
            - "./uploads:/var/www/html/wp-content/uploads"
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: "db:3306"
        networks:
            - flat-network
        env_file: .docker.env
    db:
        image: mysql:5.7
        container_name: "database"
        ports:
            - 3306:3306
        volumes:
            - "db-data:/var/lib/mysql"
        networks:
            - flat-network
        env_file: .docker.env
volumes:
    db-data:
networks:
    flat-network: